language: node_js
node_js:
  - "7"
install:
  npm install -g npm@latest
  npm --version
  npm install --registry http://registry.npmjs.org
script:
    - npm run test
    - npm run build
branches:
  only:
    - master 
after_script:
  - cd ./dist
  - git init
  - git config user.name "wangyanqin"
  - git config user.email "qin891113@yeah.net"
  - git add .
  - git commit -m "Update docs"
  - git remote add origin "https://github.com/aiqinhaian/CITest2.git"
  - git push --set-upstream origin master -f
env:
  global:
    - GH_REF: github.com:aiqinhaian/CITest2.git
