language: node_js
node_js:
  - "7"
install:
  npm install -g npm@latest
  npm --version
  npm install --registry http://registry.npmjs.org
script:
    - npm install
    - npm run test
    - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "wangyanqin"
  - git config user.email "qin891113@yeah.net"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
global:
   - GH_REF: github.com:aiqinhaian/CITest2.git
